### ISSUE TITLE
Dracut UKI with LZ4 compression shows kernel error after updating to systemd 257

### ISSUE THREAD

**Issue by Zesko** [dracut-ng/dracut-ng#1049]
**Describe the bug**

After updating to systemd 257, I get the following kernel error message when booting a UKI with LZ4 compression:
```
kernel: Initramfs unpacking failed: Decoding failed
``` 

This error only started happening after updating systemd to version 257. I **didn’t change** the kernel version and my Dracut config, which is set to `compress=lz4`. (I’m 100% sure about this.)

Here’s what I found so far:

- **Switching to zstd compression** in Dracut fixes the issue.

- **Switching back to lz4** brings the error back after rebooting.

- I’ve tested this on two different devices, both running the same versions of Dracut and systemd, and the issue is reproducible.

- Booting from a previous snapshot with systemd 256 and the older UKI works fine with no errors.

I think this might be some kind of compatibility issue between Dracut and systemd 257, but I’m not 100% sure.

**Distribution used**
Arch Linux
Kernel versions: `linux` 6.12.4 (Arch repo) and `linux-tkg` 6.12.4 (custom kernel) — both have the same issue.

**Dracut version**
Dracut 105 (from Arch official repo)

**Init system**
Systemd 257 (from Arch official repo)

**To Reproduce**

1. Update systemd to version 257.
2. Set `compress=lz4` in your Dracut config.
3. Create UKI with:
```bash
dracut --force --uefi --hostonly --no-hostonly-cmdline --kver "${kVer}" "${ukiDirPath}/${MACHINE_ID}_${kVer}.efi" --kernel-cmdline "${KERNEL_CMDLINE}"
```
4. Make sure the new UKI is loaded by your bootloader.
5. Reboot and check for the error message in dmesg or the journal.

**Expected behavior**

The kernel error message shouldn’t appear, just like it didn’t with systemd 256.

**Comment by bdrung** [comment]
Have you checked that the kernel supports lz4?

```
grep CONFIG_RD_ /boot/$kernel_config
```
