### ISSUE TITLE
Enable test for dracut-cpio

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#106]
[enable_dracut_cpio](https://github.com/dracut-ng/dracut-ng/blob/main/Makefile#L209) does not seem to be tested on any of the CI test containers (TEST-62 is skipped). 

References
 - https://github.com/dracutdevs/dracut/pull/1531
 - https://github.com/dracutdevs/dracut/issues/1662
 
 CC @ddiss (author) @bdrung (performance interest)

**Comment by ddiss** [comment]
Thanks for the ping, we enable `dracut-cpio` at build time for openSUSE and some versions of SLES. However, it requires explicit `enhanced-cpio` configuration otherwise regular GNU `cpio` is used by default.

**Comment by ddiss** [comment]
While we're here, is there any documentation regarding the intentions / backing of this fork?
