### ISSUE TITLE
systemd enabled Gentoo container fails tests

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#135]
After systemd is enabled for the Gentoo CI container tests are failing.

Hope to fix the container instead of reverting the change as we want to move forward and have systemd in Gentoo container.

See https://github.com/dracut-ng/dracut-ng/commit/76963537edcfbad21c5fa096834e982564653808

Error message

```
Could not find a Linux kernel version 6.6.21-gentoo-dist to test with!
Please install linux.
```

Link to failed run - https://github.com/dracut-ng/dracut-ng/actions/runs/8589738665/job/23536300253

```
ls /boot/
kernel-6.6.21-gentoo-dist
```

**Comment by AndrewAmmerlaan** [comment]
Those test have in common that they are testing encryption and RAID. I suspect some systemd components are missing from the initramfs because they are not installed by the systemd package.

We probably need to enable some USE flag for `sys-apps/systemd`, the question though is which one:
```
[I] sys-apps/systemd
Available versions:  254.8-r1(0/2)^t (~)254.9-r1(0/2)^t (~)254.10(0/2)^t 255.3-r1(0/2)^t (~)255.4(0/2)^t{gpkg} **9999(0/2)*l^t {acl apparmor audit boot cgroup-hybrid cryptsetup curl +dns-over-tls elfutils fido2 +gcrypt gnutls homed http idn importd iptables +kernel-install +kmod +lz4 lzma +openssl pam pcre pkcs11 policykit pwquality qrcode +resolvconf +seccomp secureboot selinux split-usr +sysv-utils test tpm ukify vanilla xkb +zstd ABI_MIPS="n32 n64 o32" ABI_S390="32 64" ABI_X86="32 64 x32" PYTHON_SINGLE_TARGET="python3_10 python3_11 python3_12"}
Installed versions:  255.4(0/2)^t{gpkg}(21:35:56 23/03/24)(acl apparmor boot cryptsetup dns-over-tls elfutils gcrypt idn iptables kernel-install kmod lz4 lzma openssl pam pcre pkcs11 policykit resolvconf seccomp secureboot sysv-utils tpmukify xkb zstd -audit -cgroup-hybrid -curl -fido2 -gnutls -homed -http -importd -pwquality -qrcode -selinux -split-usr -test -vanilla ABI_MIPS="-n32 -n64 -o32" ABI_S390="-32 -64" ABI_X86="32 64 -x32" PYTHON_SINGLE_TARGET="python3_11 -python3_10 -python3_12")
Homepage:            http://systemd.io/
Description:         System and service manager for Linux
```

Could be `cryptsetup` is the flag we are looking for. I have no experience with disk encryption and RAID so I cannot say for sure.
