### ISSUE TITLE
error: unable to write to pipe (Broken pipe)

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#166]
https://github.com/dracutdevs/dracut/issues/2628

https://forum.endeavouros.com/t/error-message-broken-pipe-during-system-update/50160/4

Only seen on Arch based distros, so this might be Arch specific. In addition not clear if the error is from Dracut, but several (3+) people reported similar issues independently even against latest versions.

@YoinkerBoinker @davidhaley @100busy

**Comment by dalto8** [comment]
I have also seen this issue intermittently.  However, I am not sure if it is coming from dracut or not.  I have only ever see it occur at the end of the last dracut image being created.

It also looks like all those reports are coming from users using kernel-install and at least two of us are using the package kernel-install-for-dracut.  Additionally, I have only seen that error when it is invoked from a pacman hook.

There are a lot of variables involved unfortunately.
