### ISSUE TITLE
close crypt devices to release encryption keys get on shutdown

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#204]
add a shutdown hook to close encrypted devices and wipe their encryption keys from kernel memory.

Related work 
 - dracutdevs/dracut/issues/997
 - dracutdevs/dracut#1888
 - dracut-ng/dracut-ng/pull/94

CC @DanWin @adrelanos

**Comment by adrelanos** [comment]
Should PR https://github.com/dracutdevs/dracut/pull/2471 be moved over, re-opened at `dracut-ng`?
