### ISSUE TITLE
with systemd 256 dracut cannot write hooks to /lib/dracut/hooks during boot because /lib is /usr/lib, which is read-only with new ProtectSystem feature

### ISSUE THREAD

**Issue by AdamWill** [dracut-ng/dracut-ng#253]
**Describe the bug**
systemd 256 has a new `ProtectSystem` feature which makes `/usr` read-only. This is set to default to on in initramfs environments. dracut's `hookdir`, where it writes hooks generated during the boot process, is `/lib/dracut/hooks`. On Fedora, `/lib` is a symlink to `/usr/lib`, so dracut winds up trying to write hooks to a read-only filesystem.

**Distribution used**
Fedora Rawhide.

**Dracut version**
060.

**Init system**
systemd.

**To Reproduce**
Update a Fedora Rawhide system to systemd 256 (from https://koji.fedoraproject.org/koji/buildinfo?buildID=2444479 ). Re-generate the initramfs with `dracut -f`. Reboot. You will see errors like `//lib/dracut/hooks/cmdline/00-parse-root.sh: line 28: /lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fdisk\x2fby-uuid\x2ff18e44fc-458a-483d-ae4f-fe5ee8ba011c.sh: Read-only file system`.

**Expected behavior**
There should be no such errors.

**Additional context**
@poettering pointed out the likely cause of these errors. There is an additional problem with systemd 256 which will cause the system to fail to boot at all unless dracut has [this change applied](https://github.com/dracut-ng/dracut-ng/pull/118); I will probably send a dracut build with that backported soon. With that patched, the system may boot (unless any boot-time hooks are actually vital to boot in your configuration) and the errors may not be so obvious, but I think they will still happen.

I've also filed this on systemd at https://github.com/systemd/systemd/issues/32511 ; it seems reasonable to have a bug report on each side, because we may want to make some adjustment in systemd in the short term, but in the long term we probably want dracut to change the hook directory to something else. It looks like this might be rather disruptive, though.

**Comment by AdamWill** [comment]
systemd change was https://github.com/systemd/systemd/pull/30255 , for reference.

**Comment by AdamWill** [comment]
oh, yeah, that looks like exactly what we need. thanks.

**Comment by pvalena** [comment]
If this is already fixed upstream, let's close this. For Fedora issues, please use https://bugzilla.redhat.com/.

**Comment by AdamWill** [comment]
In practice it's fixed by https://github.com/dracut-ng/dracut-ng/pull/194 , yes. I don't know where you want to track the whole #194 vs #114 thing, but if not here, then sure, this can be closed.

**Comment by nanonyme** [comment]
Is there a release planned anytime soon with the fix included?

**Comment by nanonyme** [comment]
Not really distribution, we're freedesktop-sdk which in addition to being used for flatpak runtimes also provides OS building blocks which are consumed by eg gnome os. We're mentally prepared to backport the patches until release is done but good to hear there will be a release with them in near months.

**Comment by jrelvas-ipc** [comment]
This also appears to affect the module blacklist, as of dracut-ng-101:

`mai 19 18:27:54 aquecedor-3-0 dracut-pre-udev[541]: /bin/dracut-pre-udev: line 40: /usr/lib/modprobe.d/initramfsblacklist.conf: Read-only file system`

**Comment by jrelvas-ipc** [comment]
Sure, I'll give it a try and report back later.

**Comment by dracutng** [comment]
> Is there a release planned anytime soon with the fix included?

new release is out - v102 - https://github.com/dracut-ng/dracut-ng/releases/tag/102

**Comment by pvalena** [comment]
AFAIR, for Fedora, I have backported the fix to `dracut-101` already.
