### ISSUE TITLE
tpm2-tss - unknown group tss reported 

### ISSUE THREAD

**Issue by Nowa-Ammerlaan** [dracut-ng/dracut-ng#274]
**Describe the bug**

From downstream Bug: https://bugs.gentoo.org/925524

After building an initrd with Dracut with systemd (which pulls in tpm2-tss module), prior to switching sysroot, these non-fatal errors will appear:

/usr/lib/tmpfiles.d/tpm2-tss-fapi.conf:2: Failed to resolve user 'tss': No such process
/usr/lib/tmpfiles.d/tpm2-tss-fapi.conf:4: Failed to resolve user 'tss': No such process
/usr/lib/tmpfiles.d/tpm2-tss-fapi.conf:6: Failed to resolve group 'tss': No such process
/usr/lib/tmpfiles.d/tpm2-tss-fapi.conf:7: Failed to resolve group 'tss': No such process
/usr/lib/udev/rules.d/60-tpm-udev.rules:3 Unknown user 'tss', ignoring.
/usr/lib/udev/rules.d/60-tpm-udev.rules:4 Unknown group 'tss', ignoring.

The tpm2-tss module does attempt to create at least the tss user via a file in sysusers.d:

https://github.com/dracutdevs/dracut/blob/master/modules.d/91tpm2-tss/module-setup.sh#L35C21-L35C35

The problem is this file tpm2-tss.conf does not exist on Gentoo machines. It is normally installed by tpm2-tss but we do not because we have acct-user/tss and the group packages.

I think the best solution to send a patch upstream so that the acct-user/acct-group files are considered as well as the standard file.

**Distribution used**
Gentoo Linux

**Dracut version**
59 and up

**Init system**
Systemd

**To Reproduce**
Build a dracut image on a Gentoo Linux system and include the tpm2-tss module

**Expected behavior**
The required user exists in the initramfs

**Additional context**
See also: https://github.com/dracutdevs/dracut/issues/1700

**Comment by AndrewAmmerlaan** [comment]
Yes probably, here's my `sysusers` dir:
```
andrew@andrew-gentoo-laptop ~ % ls /usr/lib/sysusers.d
acct-group-adm.conf      acct-group-geoclue.conf      acct-group-nm-openvpn.conf    acct-group-scanner.conf                 acct-group-usb.conf         acct-user-man.conf         acct-user-sddm.conf
acct-group-android.conf  acct-group-gpib.conf         acct-group-nobody.conf        acct-group-sddm.conf                    acct-group-users.conf       acct-user-messagebus.conf  acct-user-sshd.conf
acct-group-audio.conf    acct-group-i2c.conf          acct-group-nullmail.conf      acct-group-sgx.conf                     acct-group-utmp.conf        acct-user-mysql.conf       acct-user-systemd-coredump.conf
acct-group-avahi.conf    acct-group-input.conf        acct-group-openct.conf        acct-group-sshd.conf                    acct-group-vboxusers.conf   acct-user-nm-openvpn.conf  acct-user-systemd-journal-remote.conf
acct-group-brlapi.conf   acct-group-kmem.conf         acct-group-openvpn.conf       acct-group-systemd-coredump.conf        acct-group-video.conf       acct-user-nobody.conf      acct-user-systemd-network.conf
acct-group-brltty.conf   acct-group-kvm.conf          acct-group-pcscd.conf         acct-group-systemd-journal.conf         acct-group-wheel.conf       acct-user-nullmail.conf    acct-user-systemd-oom.conf
acct-group-cdrom.conf    acct-group-libreoffice.conf  acct-group-pipewire.conf      acct-group-systemd-journal-remote.conf  acct-user-avahi.conf        acct-user-openvpn.conf     acct-user-systemd-resolve.conf
acct-group-colord.conf   acct-group-lpadmin.conf      acct-group-plugdev.conf       acct-group-systemd-network.conf         acct-user-brltty.conf       acct-user-pcscd.conf       acct-user-systemd-timesync.conf
acct-group-dialout.conf  acct-group-lp.conf           acct-group-polkitd.conf       acct-group-systemd-oom.conf             acct-user-colord.conf       acct-user-polkitd.conf     acct-user-tss.conf
acct-group-disk.conf     acct-group-mail.conf         acct-group-portage.conf       acct-group-systemd-resolve.conf         acct-user-dnsmasq.conf      acct-user-portage.conf     brltty.conf
acct-group-dnsmasq.conf  acct-group-man.conf          acct-group-pulse-access.conf  acct-group-systemd-timesync.conf        acct-user-flatpak.conf      acct-user-postmaster.conf  sddm.conf
acct-group-docker.conf   acct-group-messagebus.conf   acct-group-render.conf        acct-group-tape.conf                    acct-user-geoclue.conf      acct-user-root.conf
acct-group-flatpak.conf  acct-group-mysql.conf        acct-group-root.conf          acct-group-tss.conf                     acct-user-libreoffice.conf  acct-user-rtkit.conf
acct-group-floppy.conf   acct-group-netdev.conf       acct-group-rtkit.conf         acct-group-tty.conf                     acct-user-mail.conf         acct-user-saned.conf
```

Basically on Gentoo these files will be prefixed with `acct-user` or `acct-group` since they are installed by virtual packages that handle and track user and group management

**Comment by Nowa-Ammerlaan** [comment]
We have a downstream patch now utilizing the mechanism introduced in your PR, so I think we can close this.
