### ISSUE TITLE
ldconfig.real

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#312]
On Debian systemd-ldconfig dracut module requires /usr/sbin/ldconfig.real binary.

Related:
 - https://bugs.launchpad.net/ubuntu/+source/dracut/+bug/2053057
 - https://github.com/dracut-ng/dracut-ng/pull/249

CC @bdrung

**Comment by bdrung** [comment]
We have a patch in Ubuntu for that.
