### ISSUE TITLE
dracut[E]: Module 'systemd-pcrphase' depends on 'tpm2-tss', which can't be installed

### ISSUE THREAD

**Issue by dalto8** [dracut-ng/dracut-ng#329]
**Describe the bug**
It seems like the systemd-pcrphase module always gets pulled into the initramfs even if it is not needed as of #256 

This results in the below message on Arch for most users.
```
dracut[E]: Module 'systemd-pcrphase' depends on 'tpm2-tss', which can't be installed
```

This was noticed by EndeavourOS user [here](https://forum.endeavouros.com/t/dracut-error/55999).  I have verified that it also occurs on a base Arch install.

This could be expected behavior but is somewhat unfortunate that most users see this message since it is probably somewhat uncommon to have `tpm2-tools` installed.

**Distribution used**
Arch Linux, EndeavourOS

**Dracut version**
102

**Init system**
systemd

**To Reproduce**
Run dracut in Arch.  Since systemd-pcrextend is part of the systemd package, it will always try to pull in this module.

**Comment by dalto8** [comment]
> As I understand, it is not pulled in.. Just an attempt to pull in as dependency evaluation eventually sorts out that this module can not be pulled in.

Yes, absolutely, it doesn't get added because the dependency fails.

I guess the core question I would have is should systemd-pcrphase be added simply because systemd is installed?  Is that the correct autodetection for that module?

**Comment by AndrewAmmerlaan** [comment]
Haven't looked into it in detail yet, but at first glance I would say the dependency makes sense since these PCR banks are on the TPM after all. In Gentoo `sys-apps/systemd[tpm]` depends on `app-crypt/tpm2-tss`, so somewhere systemd is using tpm2-tss.

**Comment by BSerpent86** [comment]
> As stated, this is just a harmless warning, but regardless, lets discuss..

In this case, the bug is that the message is categorized as Error, and not as Warning.
