### ISSUE TITLE
Regression LUKS + ZFS on root system not booting after updating to dracut 102.

### ISSUE THREAD

**Issue by PoisonFrog** [dracut-ng/dracut-ng#343]
**Distribution used**
Arch Linux

**Dracut version**
102

**Init system**
systemd

**Expected behavior**
Booting just like it was with dracut 101

**Additional context**
I have a LUKS keyfile in the initramfs built with dracut and once it opens the volume it has to detect the ZFS pool inside the encrypted volume and boot the ZFS root and it was all working for a long time till I updated to dracut 102, now it doesn't work anymore. Downgrading to dracut 101 and rebuilding initramfs makes it possible to boot again. Configuration is the same. The "crypt" and "zfs" modules were installed.

**Comment by LaszloGombos** [comment]
Would manually setting `rd.auto=0` in the kernel command line works around the problem ?

**Comment by PoisonFrog** [comment]
> Would manually setting `rd.auto=0` in the kernel command line works around the problem ?

I tried it, but it didn't work.

**Comment by LaszloGombos** [comment]
If the regression is not caused by https://github.com/dracut-ng/dracut-ng/commit/2339acfaeee60d6bb26a1103db2e53bc8f9cb2d1, than you could help by finding out which commit between 101 and 102 caused the unexpected change.

Maybe also look at the discussion at https://github.com/dracut-ng/dracut-ng/issues/333 . That might not be related but perhaps help you narrow it down what else to try (e.g. `hostonly` vs `no-hostonly`, different kernel command line options, etc.)

The issue is acknowledged, but it does not have enough information to reproduce or resolve.

**Comment by PoisonFrog** [comment]
> If the regression is not caused by [2339acf](https://github.com/dracut-ng/dracut-ng/commit/2339acfaeee60d6bb26a1103db2e53bc8f9cb2d1), than you could help by finding out which commit between 101 and 102 caused the unexpected change.
> 
> Maybe also look at the discussion at #333 . That might not be related but perhaps help you narrow it down what else to try (e.g. `hostonly` vs `no-hostonly`, different kernel command line options, etc.)
> 
> The issue is acknowledged, but it does not have enough information to reproduce or resolve.

I'm not using a TPM. I'm also explicitly defining the disk ID and keyfile in KCL for LUKS unlocking. The error I'm getting is that dracut is unable to mount sysroot because it doesn't detect a ZFS pool. I'm building with the crypt and zfs modules and I tried adding the cryptsetup binary to the initramfs to try to import the pool manually after it fails, but even after unlocking the LUKS volume manually inside initramfs I was still not able to import pools using "zpool import" because it doesn't detect any pool after unlocking the volume. At first I thought it could be a ZFS issue, but when building with dracut 101 using the same ZFS version everything works normally.

**Comment by LaszloGombos** [comment]
> At first I thought it could be a ZFS issue, but when building with dracut 101 using the same ZFS version everything works normally.

This is useful information and this does not mean that this is not an issue with the zfs dracut module. The zfs dracut module is not part of this project, it is part of https://github.com/openzfs/zfs/tree/master/contrib/dracut/90zfs .

I recommend you also raise and issue with the zfs project as the solution might require changes in the zfs project as well.

CC @znabijaczleweli as he might be able to help with this more than I do, but I do recommend involving the zfs community or reproducing the issue without zfs.

**Comment by LaszloGombos** [comment]
Related https://bugs.launchpad.net/ubuntu/+source/dracut/+bug/2070013
CC @bdrung

**Comment by PoisonFrog** [comment]
> Related https://bugs.launchpad.net/ubuntu/+source/dracut/+bug/2070013 CC @bdrung

I don't think this is related since he was lacking zfs-dracut and just needed to install it. That's not the same issue since I have zfs-dracut installed and it works with all previous versions of dracut but doesn't work with dracut 102. I don't think it is a ZFS issue since it didn't update and still works with all the Arch kernels and older versions of dracut. The only thing that has changed in my system is dracut itself.

**Comment by jozzsi** [comment]
@PoisonFrog Can you please try to add systemd-crytpsetup module (or simply try latest main branch) ? Would that resolve it - see https://github.com/dracut-ng/dracut-ng/issues/563 for context.

**Comment by PoisonFrog** [comment]
> @PoisonFrog Can you please try to add systemd-crytpsetup module (or simply try latest main branch) ? Would that resolve it - see #563 for context.

Using `dracut-git`from the AUR works. I'm closing this issue since it is fixed in the main branch. Thank you.
