### ISSUE TITLE
dracut does not check for kernel compression support

### ISSUE THREAD

**Issue by bdrung** [dracut-ng/dracut-ng#378]
**Describe the bug**

When using zstd compression, dracut checks that the kernel supports zstd compressed initrds (`CONFIG_RD_ZSTD`). But dracut does not do this check for all the other possible compression formats. So you might end up with a xz or gzip compressed initrd that cannot be read by the kernel. Please also check those kernel configs:

```
CONFIG_RD_GZIP
CONFIG_RD_BZIP2
CONFIG_RD_LZMA
CONFIG_RD_XZ
CONFIG_RD_LZO
CONFIG_RD_LZ4
```

**Dracut version**
102

**Comment by AndrewAmmerlaan** [comment]
-> https://github.com/dracut-ng/dracut-ng/pull/562
