### ISSUE TITLE
systemd v256 compatibility on CI

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#382]
As distributions are introducing systemd v256  the CI will gets the upgrade as well.
On Jun-18 Arch is the first CI container that got the systemd v256  upgrade, which broke almost all test runs.
The symptom of the breakage seems to be that Arch now seem to require systemd dracut module in the generated initrd. 
At this point of time it is not clear if this is an intentional decision only for Arch or other distributions will follow as well.

**Comment by LaszloGombos** [comment]
CC @bdrung @freswa

**Comment by scruffidog** [comment]
I assume my particular issue with trying to generate a working dracut initramfs without any systemd* modules is related to this ?

the content of /etc/dracut.conf.d/default.conf:

> early_microcode="no"
> hostonly="yes"
> hostonly_mode="strict"
> do_strip="yes"
> aggressive_strip="yes"
> compress="xz"
> squash_compress="xz"
> filesystems+=" xfs squashfs vfat "
> omit_dracutmodules+=" pcmcia i18n dracut-systemd terminfo "
> omit_dracutmodules+=" systemd systemd-network-management systemd-ac-power "
> omit_dracutmodules+=" systemd-ask-password systemd-bsod systemd-coredump systemd-creds "
> omit_dracutmodules+=" systemd-hostnamed systemd-initrd systemd-integritysetup systemd-journald "
> omit_dracutmodules+=" systemd-ldconfig systemd-modules-load systemd-networkd systemd-pcrphase "
> omit_dracutmodules+=" systemd-portabled systemd-pstore systemd-repart systemd-resolved "
> omit_dracutmodules+=" systemd-sysctl systemd-sysext systemd-sysusers systemd-timedated "
> omit_dracutmodules+=" systemd-timesyncd systemd-tmpfiles systemd-udevd systemd-veritysetup systemd-cryptsetup dracut-systemd "

I invoke the dracut command with very little commandline arguments, other than a --force as I would like to shove as much of the switches as possible within the config file. When I use the generated initramfs, the system tries to run systemd-udevd and then freezes, requiring a power-syscle to regain control. I looked at the included /init and there was explicit reference:

`[conch@borg-1 tmp]$ lsinitrd /boot/initramfs-linux.img init | grep systemd-udev
UDEV_LOG=$UDEV_LOG "$systemdutildir"/systemd-udevd --daemon --resolve-names=never
`

Is this an underlying issue with the way the dracut modules are written or is there a different way to approach the problem ?

**Comment by LaszloGombos** [comment]
> the content of /etc/dracut.conf.d/default.conf:

@scruffidog - try to omit just system dracut module, as some of the tests changes - https://github.com/dracut-ng/dracut-ng/pull/405/files#diff-831e27ecca6747ee5e7ddc6c07da3f5beff2c2fdb3ac87a47349bf959eca3c03R101

**Comment by scruffidog** [comment]
that's what I tried 1st, but then there were the same remnants as with the subsequent comprehensive omission of all systemd* modules, which does not seem to help...
