### ISSUE TITLE
Install weak dependencies from kernel modules

### ISSUE THREAD

**Issue by aafeijoo-suse** [dracut-ng/dracut-ng#383]
https://github.com/kmod-project/kmod/commit/05828b4a6e9327a63ef94df544a042b5e9ce4fe7
https://lore.kernel.org/lkml/20240510085726.327831-1-jtornosm@redhat.com/

**Comment by LaszloGombos** [comment]
@jtornosm @aafeijoo-suse would you consider this issue fixed now after the PR is committed ? Just wondering if we should keep this open and if so why. Thanks !

**Comment by jtornosm** [comment]
Since I didn't open it, I didn't dare to close it.
@LaszloGombos For me the issue is fixed because now it is supported and we can close the issue.
