### ISSUE TITLE
Crypt module fails to find LUKS with systemd newer than 255.7

### ISSUE THREAD

**Issue by farfalleflickan** [dracut-ng/dracut-ng#387]
**Describe the bug**
After upgrading systemd (and related packages) from 255.7 to 256.3, my config stopped working.
My current config: 
```
add_dracutmodules+=" crypt rootfs-block crypt-gpg "
omit_dracutmodules+=" qemu qemu-net btrfs network net-lib connman virtiofs usrmount cifs nfs "
omit_dracutmodules+=" dracut-systemd systemd systemd-networkd systemd-initrd i18n systemd-udevd rngd memstrack "
force_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "
install_items+=" /etc/dracut.conf.d/keyfile.gpg "
kernel_cmdline+=" rd.luks.uuid=luks-4a71392e-7b47-43be-855c-0e8631e83f49 rd.luks.key=/etc/dracut.conf.d/keyfile.gpg:/ rd.lvm.lv=SSD/root root=/dev/mapper/SSD-root rootfstype=ext4 rootflags=rw,noatime rd.luks.smartcard=1 rd.auto=0 rd.systemd.gpt_auto=0 rd.shell rd.debug "
```
I omit all systemd modules in order to use crypt-gpg to decrypt my LUKS partition, otherwise systemd catches the LUKS partition and tries decryption with a password (instead of trying to use a gpg key/smartcard first).

Just to try I enabled the systemd modules and I can boot fine (although by using a password, not by using crypt-gpg/a smartcard).

I managed to grab a couple of "screenshots" (I was unable to get it to dump a log anywhere as no keyboard would work, so I resulted to this, sorry...).

![1](https://github.com/dracut-ng/dracut-ng/assets/6597735/000b2593-d9b0-4b16-b488-e0c114f9ba58)
![2](https://github.com/dracut-ng/dracut-ng/assets/6597735/ed7e4ca5-e42f-451a-ba06-80e71b4c0972)

**Distribution used**
Arch Linux

**Dracut version**
102 (same in 101)

**Init system**
systemd

**To Reproduce**
Use crypt module and install systemd > 255.7

**Expected behavior**
Should find the partition and work normally as it used to.

**Comment by LaszloGombos** [comment]
> I omit all systemd modules...systemd catches the LUKS partition and tries decryption with a password

You could try to omit only certain systemd dracut modules, not all of them (e.g. omit systemd-cryptsetup, but not systemd-udevd).

Not sure, if this is an issue with Arch packaging, systemd >=> 256 or dracut itself, but CI run into similar issue - https://github.com/dracut-ng/dracut-ng/issues/382

**Comment by farfalleflickan** [comment]
I forgot to write it, I tried but that unfortunately does not work... I was finally able to get out the [log](https://github.com/user-attachments/files/15920655/rdsosreport.txt) (only omitted hook is systemd-cryptsetup). 

I am going to investigate it further tomorrow but after a quick look I noticed that it seems to try to start sytemd-cryptsetup, which it does not have...

**Comment by farfalleflickan** [comment]
After some sleep and some investigation, I think the issue is in 90crypt/parse-crypt.sh, although I am not knowledgeable enough to really get 100% what's going on. 
Using the emergency shell I can confirm that the LUKS disk is in /dev/disk/by-uuid but parse-crypt.sh obviously does not seem to pick it up...

**Comment by LaszloGombos** [comment]
> no keyboard would work

Possible workaround discussion:
https://github.com/zbm-dev/zfsbootmenu/issues/648#issuecomment-2224147934

**Comment by farfalleflickan** [comment]
Adding libkmod seemed to fix all issues! Thanks!
