### ISSUE TITLE
systemd-pcrphase for Gentoo CI container

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#481]
https://github.com/dracut-ng/dracut-ng/issues/92 can not be reproduced on the Gentoo container.

I hope to at least confirm that systemd-pcrphase can be installed in the FULL_SYSTEMD test. Other systemd enabled containers already have support for systemd-pcrphase, except Gentoo.

CC @AndrewAmmerlaan

**Comment by AndrewAmmerlaan** [comment]
I'm not sure I understand the issue. Is the problem that systemd-pcrphase is not included specific to Gentoo? What exactly should I test?

**Comment by LaszloGombos** [comment]
Issue is just with the Gentoo Docker file, to make sure that dependent binaries are in the Docker image for https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/01systemd-pcrphase/module-setup.sh#L9 . Thanks !
