### ISSUE TITLE
Rescue initrd not showing prompt

### ISSUE THREAD

**Issue by pvalena** [dracut-ng/dracut-ng#492]
**Describe the bug**

Rescue initrd should always show the options for entering shell, instead of trying to decrypt the root disk.

Most probably caused by PR #320 - which I propose to revert.

Different defaults per-module is a mess, and probably causes this issue: https://bugzilla.redhat.com/show_bug.cgi?id=2295215

IMO the change should've been made in configuration of the specific distro (`rd.auto=1`); either on command line, or i `dracut.conf`, not by changing defaults for everyone without adding any overall benefit; or clear reasoning for the change.

**Distribution used**
Fedora 40+

**Dracut version**
101 + patch from PR373

**Init system**
Systemd

**To Reproduce**
- Have encrypted root disk
- create new rescue disk.
- Boot the rescue disk.

**Expected behavior**
prompt for "Continue", "Read-only mount" or "Skip to shell"

**Comment by LaszloGombos** [comment]
> Most probably caused by PR #320 - which I propose to revert.

@pvalena From the bugzilla report it seems that reverting 2339acfaeee60d6bb26a1103db2e53bc8f9cb2d1 resolve the issue for Fedora. Can you confirm ?

**Comment by Conan-Kudo** [comment]
Let's just proceed to revert it and move things along.
