### ISSUE TITLE
retire ifcfg module

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#503]
This module is potentially used by Fedora and it is also used by some of the tests in the CI. 

The project should make steps towards having an agreement in place foe the timeline of this module and remove it from the upstream tree .

@pvalena

**Comment by dtardon** [comment]
> This module is potentially used by Fedora

Not any more. Support for `ifcfg` files was obsoleted by NetworkManager in Fedora 33 and [removed](https://fedoraproject.org/wiki/Changes/MigrateIfcfgToKeyfile) in Fedora  39. That means it's not available in _any_ supported Fedora release.

**Comment by LaszloGombos** [comment]
CC @steffen-maier for s390
