### ISSUE TITLE
Dracut now has many dependencies on systemd-modules-load, requiring building modules support into systemd.

### ISSUE THREAD

**Issue by AndreMullinger** [dracut-ng/dracut-ng#510]
**Describe the bug**
With the recent rework/expansion of systemd integration in dracut-10x,
quite a few dependencies now tie in systemd-modules-load unconditionally.
Which in turn requires module support compiled into systemd.
I use dracut for UKIs with monolithic kernels, it would be nice to have those handled.
The ramdisk's job is to unlock the root file system using a pcr measurement + pin.

That said, I'm aware of the ancient workaround monolithic kernels require (for hostonly) anyway
https://github.com/dracutdevs/dracut/issues/56
so this may well not have priority and rather be a feature request/maintenance load/...

I'll probably file a request https://github.com/gentoo to have dracut depend on systemd[kmod]
if the dep is here to stay :) Thanks!

**Distribution used**
Gentoo

**Dracut version**
102

**Init system**
 systemd-256.1

**To Reproduce**
Using systemd-256.1 without support for kernel modules compiled in,
creating the UKI fails due to unsatisfied dependencies.

**Expected behavior**
Even more complex environment tests at runtime?

**Additional context**
I originally filed this as https://github.com/dracutdevs/dracut/issues/2664 in error, and was redirected here.

**Comment by LaszloGombos** [comment]
CC @AndrewAmmerlaan

**Comment by jozzsi** [comment]
@AndreMullinger thanks for the report.

> creating the UKI fails due to unsatisfied dependencies.

Can you please share the exact error message to have a better understanding how this should be addressed ? 

> I'm aware of the ancient workaround monolithic kernels require (for hostonly) anyway

`--no-kernel` would not work as a workaround ?

**Comment by AndreMullinger** [comment]
@jozzsi thanks for picking it up!

The error messages are:
`
# DRACUT_KERNEL_MODALIASES="/root/UKIstore/empty_dummy" dracut /tmp.bla
dracut[I]: Executing: /usr/bin/dracut /tmp.bla
dracut[E]: Module 'systemd-sysctl' depends on module 'systemd-modules-load', which can't be installed
dracut[E]: Module 'systemd-udevd' depends on module 'systemd-sysctl', which can't be installed
dracut[E]: Module 'tpm2-tss' depends on module 'systemd-udevd', which can't be installed
dracut[E]: Module 'systemd-cryptsetup' depends on module 'tpm2-tss', which can't be installed
dracut[E]: Module 'systemd-initrd' depends on module 'systemd-udevd', which can't be installed
dracut[E]: Module 'dracut-systemd' depends on module 'systemd-initrd', which can't be installed
dracut[E]: Module 'systemd-cryptsetup' depends on module 'tpm2-tss', which can't be installed
`

--no-kernel seems to imply not building 'hostonly'? 
`
# dracut --no-kernel /tmp/bla
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
dracut-install: Could not get list of loaded modules: Unknown error -2. Switching to non-hostonly mode.
dracut[I]: Executing: /usr/bin/dracut --no-kernel /tmp/bla
`

That said, no-hostonly ramdisks generally works for me, and it does not look terribly bloated as well -- I have not compared the builds.

And finally:
Commenting out the "echo systemd-modules-load" from the dependencies of 01systemd-sysctl/module-setup.sh indeed allows building the uki with systemd[-kmod], i.e. without kmod support compiled in systemd. Also, I successfully boot-tested the UKI. So yes, dropping the dep works for me.
