### ISSUE TITLE
Updated `systemd-networkd` module in v103 brings in unwanted DHCP config

### ISSUE THREAD

**Issue by spijet** [dracut-ng/dracut-ng#618]
**Describe the bug**
After updating Dracut to version 103 on one of the servers I manage, the server is unable to bring up its network interfaces properly inside initramfs.

**Distribution used**
Current Gentoo (Hardened, no-multilib, systemd).

**Dracut version**
[`sys-kernel/dracut-103-r2`](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-kernel/dracut/dracut-103-r2.ebuild) from Gentoo Portage tree.

**Init system**
[`sys-apps/systemd-255.7-r1`](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/systemd/systemd-255.7-r1.ebuild) from Gentoo Portage tree.

**To Reproduce**
1. Have a Gentoo node that uses [`dracut-crypt-ssh`](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/) for remote LUKS unlock;
2. Have a network config that requires a bonding interface to be brought up with a static IP configuration in order to be reachable;
3. Have no `ip=` or similar options in kernel/initramfs cmdline, all network configuration is copied over from the root filesystems' `/etc/systemd/network` directory;
4. Upgrade Dracut from version [`060_pre20240104-r4`](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-kernel/dracut/dracut-060_pre20240104-r4.ebuild) (the previous "stable" version) or from version [`102`](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-kernel/dracut/dracut-102.ebuild) (currently marked as "unstable" in Gentoo) to version `103-r1` and rebuild the initramfs;
5. Reboot. Because of the extra configuration files added by the new `systemd-networkd` module, the bonding interface fails to go online and the kernel logs various errors related to this interface, like it having more physical interfaces tied to it than it's supposed to have, etc.

**Expected behavior**
The `systemd-networkd` module should only add these new config files and hooks when needed and/or when asked by the system administrator.

**Additional context**
Here's how the servers' `/etc/systemd/network` directory looks like:
```
some-node ~ # ls -lah /etc/systemd/network
total 41K
drwxr-xr-x 2 root root   9 Aug 28 11:18 .
drwxr-xr-x 6 root root  17 Aug 28 04:43 ..
-rw-r--r-- 1 root root  73 Aug 28 11:18 bond0-members.network
-rw-r--r-- 1 root root 148 Apr 23 18:07 bond0.netdev
-rw-r--r-- 1 root root 339 Apr 23 22:14 bond0.network
-rw-r--r-- 1 root root 321 May 28 00:20 eno1.network
```

And here's the config (with IP addresses redacted):
```ini
## bond0-members.network
[Match]
Name=enp6s0f0 enp6s0f1

[Link]
RequiredForOnline=no

[Network]
Bond=bond0
####

## bond0.netdev
[NetDev]
Name=bond0
Kind=bond

[Bond]
Mode=802.3ad
MIIMonitorSec=1s
LACPTransmitRate=fast
UpDelaySec=2s
DownDelaySec=8s
TransmitHashPolicy=layer2+3
####

## bond0.network
# External world-reachable network
[Match]
Name=bond0

[Network]
Gateway=192.168.XXX.YYY
# Disable any dynamic addressing
# for both IPv4 and IPv6:
DHCP=no
IPv6AcceptRA=no
LinkLocalAddressing=no

[Address]
Address=192.168.XXX.ZZZ/24
Scope=link

[Address]
Address=A.B.C.D/32
Scope=global
####

## eno1.network
# Site-local OOB network
[Match]
Name=eno1

[Network]
Address=192.168.XXX.YYY/24
# Disable any dynamic addressing
# for both IPv4 and IPv6:
DHCP=no
IPv6AcceptRA=no
LinkLocalAddressing=no

[Route]
Destination=192.168.XXX.0/24
Gateway=192.168.XXX.ZZZ
Metric=200
####
```

On Dracut versions `060` and `102` the `etc/systemd/network` directory inside the generated initramfs is identical to the same directory on the root filesystem. Version `103` adds a new file, `99-dracut-default.network`, which seems to somehow mess up with the existing config. Maybe these new config files and hooks should only be added if a certain option is present in the cmdline (e.g. `netroot=<...>`)? Or maybe it would be better to extract this new functionality into a new module?

**Comment by LaszloGombos** [comment]
CC @BtbN for visibility

**Comment by BtbN** [comment]
I don't really immediately understand how the default config would mess with some bond device.
All it does is pick up any leftover unconfigured interfaces (ones which no lower-numbered .network file matches) and attempts DHCP on them.

**Comment by BtbN** [comment]
Oh, I see it. Your files don't follow the normal naming scheme.
So 99-... will sort before all your .network files.

Easy fix would be to name them all 00-.... or put them in some sensible order.

We could rename dracut-provided default file to zzzz-default-network instead of 99, to make absolutely double-tripple sure it will be sorted to the very end.

**Comment by spijet** [comment]
I may have missed the sort-prefix part in `networkd`'s docs, sorry. 😅 Tomorrow I'll try to sort the config files in some order that would make sense and try again, will let you know if it works in this case.

As for renaming the `default.network` file, so it has the `zzzz-` prefix — yes please! That way it'd go more into the "least surprise" territory. :)

**Comment by spijet** [comment]
Hello again. :)

I tried re-arranging the config files and adding numeric prefixes to them, and it seems that it fixed the main issue — the network is now working properly. But now there's another (minor) problem: now it takes more time until the server starts responding to pings and SSH connections. I assume this happens because some of the unused network interfaces get matched by this new default configuration. Will poke around more and report back if I find anything.

**Comment by BtbN** [comment]
It's most likely because dracut is now actually waiting for networkd to bring the network online before continuing, before the patches, it had no such provisions whatsoever.
The way it's programmed makes it continue the moment the first interface is considered "online" by networkd.
Shouldn't be more than a few seconds though.
