### ISSUE TITLE
Failed to add dependency on unit: Unit systemd-vconsole-setup.service does not exist from git HEAD

### ISSUE THREAD

**Issue by gene-git** [dracut-ng/dracut-ng#620]
**Describe the bug**
After commit 5551746088633116a28f3ded9d7003f378b6cd17 running dracut leads to above message

I do note that systemd-vconsole-setup.service is certainly available:

```
pacman -Qo /usr/lib/systemd/system/systemd-vconsole-setup.service
/usr/lib/systemd/system/systemd-vconsole-setup.service is owned by systemd 256.5-1
```

**Distribution used**
Archlinux

**Dracut version**
git head as of above commit

**Init system**
systemd

**Comment by jozzsi** [comment]
@gene-git The message you're seeing is coming from within the initrd, where in your current setup `systemd-vconsole-setup.service` is not included in the initrd even thought it is available in the host.

Would you be able to help and check if https://github.com/dracut-ng/dracut-ng/pull/621 resolves the message for you ? Best to test both with `10i18n` dracut module included and omitted in the generated initrd.

**Comment by gene-git** [comment]
Sure - is this sufficient?

git fetch origin pull/621/head:test
build, installed and ran dracut 

The message is gone.

PS i have nothing set up for i8n.
