### ISSUE TITLE
systemd-tmpfiles: /etc/tmpfiles.d/mytmpfile.conf:1: Failed to resolve user 'myuser': No such process

### ISSUE THREAD

**Issue by steffenweber** [dracut-ng/dracut-ng#625]
**Describe the bug**
I've upgraded a system from Dracut 060 to 103. Now, an error is logged during startup:

```
systemd-tmpfiles: /etc/tmpfiles.d/mytmpfile.conf:1: Failed to resolve user 'myuser': No such process
```

systemd-tmpfiles is launched again (successfully) after Dracut has done its job. So there is no harm done but the error message can be confusing.

**Distribution used**
Gentoo Linux

**Dracut version**
103

**Init system**
Systemd 255

**To Reproduce**
I guess this is caused by the following file:

```
$ cat /etc/tmpfiles.d/mytmpfile.conf 
f /run/mylockfile.lock 0600 myuser mygroup -
```

**Expected behavior**
No error.

**Additional context**
I see that a dependency on systemd-tmpfiles was added in Dracut 102 (https://github.com/dracut-ng/dracut-ng/commit/860b35c38ea8764e75aed3d5fca8b811b026f2a6). Maybe this has created a dependency on some kind of systemd user service that now needs to be loaded, too?

**Comment by jozzsi** [comment]
@steffenweber Are you using dracut in hostonly configuration ?

**Comment by steffenweber** [comment]
I'm calling "make install" which in turn uses Dracut and it seems like it is not using hostonly mode:

```
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
dracut-install: Could not get list of loaded modules: Unknown error -2. Switching to non-hostonly mode.
dracut[I]: Executing: /usr/bin/dracut -f --verbose --kernel-image /usr/src/linux/arch/x86/boot/bzImage --no-uefi --kver 6.6.48 /tmp/kernel-install.staging.wNf6c2/initrd
```

(My kernel doesn't have modules support which somehow makes Dracut switch to non-hostonly mode.)

**Comment by jozzsi** [comment]
> ```
> $ cat /etc/dracut.conf.d/mydracutconfig.conf 
> compress="zstd"
> hostonly="yes"
> no_kernel="yes"
> ```

What happens when you switch hostonly to "no" ? Would this change impact the issue you reported ?
