### ISSUE TITLE
Gentoo CI container fails to build

### ISSUE THREAD

**Issue by jozzsi** [dracut-ng/dracut-ng#630]
https://github.com/dracut-ng/dracut-ng/actions/runs/10644916381

@AndrewAmmerlaan can you please help to check if this would require a PR or expected to recover over time ? Thanks !

**Comment by AndrewAmmerlaan** [comment]
Caused by: https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/kernel-build.eclass?id=660b9cf9f08fd27fca32f1bd1bd8e95ee7a635bc

Should be resolved by: https://github.com/dracut-ng/dracut-ng/pull/631
