### ISSUE TITLE
remove dependency on dpkg-architecture

### ISSUE THREAD

**Issue by jozzsi** [dracut-ng/dracut-ng#644]
**Describe the enhancement**
Eliminate the usage of `dpkg-architecture` introduced by https://github.com/dracut-ng/dracut-ng/commit/4adeefc4abb8fb1d83e483d12da6b337c486fded to make the plymouth module more portable.

CC @bdrung

**Comment by bdrung** [comment]
Yes, `dpkg-architecture` should not be used. This binary is shipped by dpkg-dev which is not installed on default installations.
