### ISSUE TITLE
nvidia/nouveau, plymouth and /etc/modprobe.d

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [dracut-ng/dracut-ng#674]
**Describe the bug**
On systems that blacklist the `nouveau` module, it can still be pulled into the initramfs if the `drm` modules is included, which is pulled in by `plymouth`.

This would not be a huge issue, just a waste of space, if not for the fact that the config file blacklisting the `nouveau` module usually is in `/etc/modprobe.d` which is not included if `hostonly=no`.

End result is that on systems intending to use the nvidia driver and that have plymouth installed, the nouveau driver is loaded instead.

**Distribution used**
Gentoo

**Dracut version**
103 and up

**To Reproduce**
- install plymouth
- blacklist `nouveau` in `/etc/modprobe.d`
- set `hostonly=no`
- generate initramfs

**Expected behavior**
Either:
- a blacklisted module is never included in the initramfs, or
- `/etc/modprobe.d` is always included in the initramfs, or
- `nvidia-drivers` installs a dracut config snippet to also omit `nouveau.ko` (a downstream solution)

The first solution is better, since it saves space, but is also probably more complex to implement.

**Additional context**

CC'ing gentoo maintainers of nvidia-drivers @ionenwks @SoapGentoo 

This issue is exposed as an unintended side-effect of https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=f439b4ec05b1982f06f67fbf39a46ae0db187a76 (i.e. downstream we explicitly omit `nvidia-drivers` since it is an out-of-tree kernel module without the `initramfs` flag https://bugs.gentoo.org/928271 https://bugs.gentoo.org/932781). End result is `nouveau.ko` in the initramfs (because `drm` is included), but no `nvidia.ko` (because Gentoo configures dracut to omit it), and no blacklist (because no hostonly).

See also: https://forums.gentoo.org/viewtopic-p-8840216.html#8840216

**Comment by ionenwks** [comment]
>nvidia-drivers installs a dracut config snippet to also omit nouveau.ko (a downstream solution)
>...
>CC'ing gentoo maintainers of nvidia-drivers @ionenwks

Alternatively, maybe nvidia-drivers could just install a config file to always include `/etc/modprobe.d/nvidia.conf`? There's other important settings in there, and I wouldn't want it to be unused by accident, and it's just a small text file. Not familiar with dracut at all, but I guess install_items can do that from a peek at dracut.conf man page.

**Comment by jozzsi** [comment]
/usr/lib/modprobe.d/nvidia.conf is a better place as dracut will always include that directory.

**Comment by ionenwks** [comment]
> `/usr/lib/modprobe.d/nvidia.conf` is a better place as dracut will always include that directory - see [kernel-modules](https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/90kernel-modules/module-setup.sh#L151)

Users are invited to edit that .conf file to change settings to their liking/needs, so /etc was chosen as a more user-friendly location.

**Comment by jozzsi** [comment]
The meaning of `hostonly=no` is to make sure user changes are ignored. Dracut has no way of doing it for most files under /etc. Not sure how this bug  is actionable for dracut.

Fedora sets hostonly=yes by default during installation of the dracut package.

**Comment by AndrewAmmerlaan** [comment]
> Not sure how this bug is actionable for dracut.

The point is that a) it is weird that a module that is blacklisted is included in the initramfs, and b) that the file blacklisting it is also not included. This makes that the initramfs behaves completely different compared to the rootfs. Regardless of the hostonly setting I'd consider this discrepancy in behaviour an issue.

> Fedora sets hostonly=yes by default during installation of the dracut package.

I suppose we could do that too, but changing this now is potentially painful for users who are not paying attention to the news items.

**Comment by jozzsi** [comment]
>  but changing this now is potentially painful for users who are not paying attention to the news items.

Well, both Gentoo and Arch wiki asking to make hostonly default to yes. https://wiki.gentoo.org/wiki/Dracut , https://wiki.archlinux.org/title/Dracut .  I suppose if the user actually follows the wiki and has a setting than changing the default does not have an impact, but I agree this is a big change.

**Comment by jozzsi** [comment]
> The point is that a) it is weird that a module that is blacklisted is included in the initramfs, and b) that the file blacklisting it is also not included. This makes that the initramfs behaves completely different compared to the rootfs. 

The dracut documentation could do a better job explaining non-hostonly, but generic (non-hostonly) mode is really only meant for live-iso generation and it is defined so that it is expected to ignore hostonly changes under /etc. Generic initrd by design requires to re-specify in e.g. grub what initrd should do and should not do (e.g. when it comes to blacklisted modules).

I understand you find it weird, but what you find wired is literally how non-hostonly is defined by design, which is why I think making non-hostonly the default is "weird".

I am wondering what really upstream can do about this. There are many similar bugs filed (e.g. for encrypted root), where users are surprised that non-hostonly really does mean non-hostonly.

**Comment by AndrewAmmerlaan** [comment]
Okay, I see your point. 

I don't like this situation, but I also cannot see a proper solution. Nvidia-drivers inherently requires some user configuration to choose which driver is used, and this configuration must live in /etc otherwise the package manager may silently overwrite it. Changing the hostonly default (whether upstream or downstream) is going to be messy, and is undoubtedly going to break something for someone.

Anyway, we have a downstream workaround which effectively always includes this config file, so for Gentoo this particular problem is resolved. But I'm afraid we are going to see similar problems due to local configuration files being ignored by default. Perhaps the least painful way to improve the situation is to default to hostonly=yes, but only for new installations, though I am not sure if and how this could be done upstream so perhaps we should just write some logic for that on our end.

**Comment by Nowa-Ammerlaan** [comment]
> @Nowa-Ammerlaan What do you think about introducing a USE option for hostonly ? 
> 
> What would be the most "Gentoo-y" way to allow and encourage users to opt-in to hostonly mode to start gathering feedback and perhaps prepare for a possible transition ? 

We don't usually create USE flags that only change runtime behaviour, togeling such a flag would trigger an unnecessary recompile.
