### ISSUE TITLE
With encrypted root + unencrypted boot + systemd, dracut may generate an initrd incapable of decrypting the root disk without showing any warnings or errors

### ISSUE THREAD

**Issue by ArrayBolt3** [dracut-ng/dracut-ng#684]
**Describe the bug**
If:

* Your system is installed with root (`/`) encrypted,
* And `/boot` is on a separate, unencrypted partition,
* And you do not have `systemd-cryptsetup` installed,
* And systemd is being used within dracut,
* Then dracut will generate an initrd that is unable to decrypt the root partition on next boot. No errors are generated when this happens.

**Distribution used**
Debian 13 (Testing/Trixie)

**Dracut version**
103

**Init system**
systemd

**To Reproduce**
* Install Debian 13 Live XFCE into a VirtualBox VM, using manual partitioning to create a setup wherein `/boot` is unencrypted and root is encrypted.
* Reboot, decrypt the disk, and log in.
* Run `sudo apt install dracut`, notice that no errors about disk encryption are displayed after dracut generates an initrd for the system.
* Reboot. You will never be given a disk decryption prompt and the system will be unbootable.

**Expected behavior**
A disk decryption prompt should be given and the system should be bootable. If dracut is missing dependencies that are required for this to work, it should display an error message warning the user that they may be unable to boot with the current initrd.

**Additional context**
The root cause of this problem is the fact that `systemd-cryptsetup` is not a dependency of dracut. The 90crypt module requires either cryptsetup OR systemd-cryptsetup to exist, and dracut will install the module if either are present. cryptsetup is present in the Debian install made above, so 90crypt is installed. However, in the actual installation code, cryptsetup is only copied into the initrd if systemd is NOT in use. Debian uses systemd, and so cryptsetup gets missed, and systemd-cryptsetup doesn't exist at all so it also gets omitted. Thus the generated initrd has no way to decrypt the root partition.

Ultimately the failure to boot is a Debian packaging flaw, however it seems to me that dracut should say *something* when a situation like this arises. Perhaps if systemd is in use, the root partition is encrypted, and systemd-cryptsetup is missing, 90crypt can print a warning like `WARNING: system requires systemd-cryptsetup to be bootable but it was not found! Your system may fail to boot` in the `install()` function of `modules.d/90crypt/module-setup.sh`.

**Comment by jozzsi** [comment]
> Ultimately the failure to boot is a Debian packaging flaw

@ArrayBolt3  Do you have a Debian bug for this packaging flaw to understand better Debian plan of action ? 
As you described this can impact other apps on Debian not just dracut.

CC @bdrung

**Comment by ArrayBolt3** [comment]
@jozzsi @bdrung https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078792 (not my bug report, I was working on fixing the bug, my comment is [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078792#15))

**Comment by jozzsi** [comment]
Thanks @ArrayBolt3 

Would the following commit (tah twill be released in v104) result in an error during initrd generation - and as such resolve this issue - https://github.com/dracut-ng/dracut-ng/pull/609 ? Would it be possible for you to test ?

**Comment by ArrayBolt3** [comment]
That does look like it would fix it, I'll test. Didn't think to look for duplicates in closed bug reports (and my search term when I went to look for dupes wouldn't have matched that one anyway), sorry about that.

**Comment by jozzsi** [comment]
@ArrayBolt3 Would it be ok to close this issue given that this is no longer an issue with the latest commit  ?

**Comment by ArrayBolt3** [comment]
Sure. I haven't managed to get to the testing (been too busy), but if it isn't fixed we can reopen.

**Comment by ArrayBolt3** [comment]
I can verify the linked commit works as intended. I wish the error stood out a little more noticeably, but it's there. Thank you!
