### ISSUE TITLE
Stuck unlocking extra (unneccessary) encrypted drives

### ISSUE THREAD

**Issue by thialfi17** [dracut-ng/dracut-ng#698]
**Describe the bug**
I am trying to test various boot setups for encryption/secure boot/initramfs etc which I am doing on a spare SSD. I have other drives connected to the system that are also encrypted via LUKS and when I try and boot into this new install it first prompts me to unlock the root partition (good) but then prompts me to unlock these other drives.

I won't/can't unlock those drives since they are configured with fido2 and a very long backup passphrase and I just get prompted for the passphrase. These drives are not listed in the crypttab file - only the root drive is - and are not required for a working system and yet I don't seem to be able to get past the unlock stage for these drives.

I ran dracut with `--hostonly` which is why I have the crypttab file which only lists the root drive. I haven't been able to find any documentation that indicates blocking on the other drives is expected or how to  bypass them. Surely dracut should only block on the root drive (and potentially anything else that is listed in the crypttab file)?

**Distribution used**
Arch Linux

**Dracut version**
dracut 103

**Init system**
dracut (hostonly) + systemd-ukify with LUKS encrypted drives (for existing install) + encrypted root partition (for test install)

**To Reproduce**
Fresh arch install with dracut instead of mkinitcpio and systemd-ukify + dracut-ukify for UKI generation.
Have extra encrypted drives connected that aren't listed in the crypttab file and try booting without unlocking them.

**Expected behavior**
I expected to have to unlock the root drive and then be given access to a login prompt.

**Additional context**
This doesn't seem like all that uncommon a situation - e.g. if I had an encrypted portable drive I might plug it in before booting up but I wouldn't expect the drive to require decrypting before I could boot.

I am new to dracut, but I have read through the Arch Wiki (very limited for dracut), the man pages and various issues blog posts but didn't find anything obviously relevant.

**Comment by jozzsi** [comment]
> I ran dracut with `--hostonly` which is why I have the crypttab file which only lists the root drive. I haven't been able to find any documentation that indicates blocking on the other drives is expected or how to bypass them. 

Would `rd.auto=0` kernel command line option help  in this situation ?

**Comment by thialfi17** [comment]
Thank you for your help, I tried it and didn't see any changes which prompted me to re-read the man pages again and I think I've realised where I've gone wrong. I was putting my cmdline changes into /etc/cmdline.d/* on the host system but after a more thorough read, it looks like that's the location the files are meant to end up in the initramfs and I wasn't "installing" them so they were completely useless... There's also an option `rd.luks.uuid=`  which claims to limit interactions to listed devices which I will try.

**Comment by thialfi17** [comment]
Okay the `rd.luks.uuid` option worked. Thanks again for your help.
