### ISSUE TITLE
Updating to 104 changed used keymap in initramfs to 'en'

### ISSUE THREAD

**Issue by Emporea** [dracut-ng/dracut-ng#709]
OS: EndeavourOS

I was struggling to decrypt on startup. After several attempts, I checked if the keymap was wrong and it was.
I'm not sure if this is caused by dracut, but it happened after a reboot right after I upgraded from 103-2 to 104.

**Comment by dalto8** [comment]
Just an FYI that we are getting many reports of this issue on EndeavourOS since we use dracut by default.

I have posted a link to the issue, so hopefully someone who is experiencing the issue can help with testing.
