### ISSUE TITLE
live image is not being fetched when using `root=live:http://`

### ISSUE THREAD

**Issue by gmileka** [dracut-ng/dracut-ng#719]
**Describe the bug**
We are trying to use Dracut's livenet module to fetch an live image at boot time. We are doing that by specifying `root=live:http://image-url`. However, the image is never downloaded.

Looking at the code base, we see that livenetroot.sh is supposed to be downloading the image and then calling into dmsquash-live.sh to complete the rootfs mounting/pivoting. I am unable to find any place in the Dracut code base that calls livenetroot (or livenetroot.sh) - so, I am not sure of the status of that feature.

**Distribution used**
Azure Linux 3.0

**Dracut version**
102

**Init system**
systemd, using systemd-networkd

**To Reproduce**
- use Dracut to create an initrd image that includes the livenet module.
- create a root file system image and place it at `http://image-url`.
- update the grub.cfg with `root=live:http://image-url`.
- place all the artifacts on a PXE server.
- boot a PXE client machine.

After the kernel starts and initrd is initialized, the rootfs is never downloaded.

**Expected behavior**
Dracut's livenet module (or another agent) should attempt to download the live image specified in the `root` value.

**Additional context**
The main question is:
- how is Dracut's livenet `livenetroot.sh` expected to be called?

This [bug](https://github.com/dracutdevs/dracut/issues/1822) seems related, but it has no conclusion either.

**Comment by gmileka** [comment]
thx @jozzsi for the quick response.

Our images are using systemd's systemd-networkd. I believe I can't switch to network-legacy because of that (not sure what it uses under the covers).

Looking at 105, doing a grep on `livenetroot` shows that it is not being called anywhere still.

systemd's network stack seems to be up and running fine actually. I'm able to patch the livenet module such that it schedules the download once the network is up, and that workaround works and confirms that the network stack is fine (plz, see temporary [mitigation workaround PR](https://github.com/microsoft/azurelinux/pull/10706)).

**Comment by BtbN** [comment]
If you are on 102, the networkd module will not call any netroot scripts whatsoever.
The mentioned PR added that functionality, and was first released in 103.

**Comment by gmileka** [comment]
thanks for the suggestions jozzsi and BtbN - let me pick up 105 and give it a try.

**Comment by gmileka** [comment]
I've moved to using Dracut 105, and this indeed solves the problem I was seeing.
For reference, here are the kernel command-line parameters I'm using:
```bash
  root=live:http://192.168.0.1/azl-os/pxe-20241023-1744.iso \
  net.ifnames=0 \
  rd.live.image \
  rd.live.dir=liveos \
  rd.live.squashimg=rootfs.img \
  rd.live.overlay=1 \
  rd.live.overlay.overlayfs \
  ip=dhcp
```

thanks so much @jozzsi and @BtbN

**Comment by gmileka** [comment]
Also for reference re. "how does livenetroot get called?"
- parse-livenet.sh sets `netroot` variable to be `livenet:url`. The `livenet` prefix is later used to determine the handler.
- when the udev is settled, `networkd-run.sh` gets called - which then calls `46net-lib/netroot.sh`.
- `netroot.sh` concatenates the prefix of the `netroot` variable contents to compose the name of the script to call (this is why a grep of `livenetroot` will not return any calls in the code base).

https://github.com/dracut-ng/dracut-ng/blob/8b7367eff06d46476e3c94a98bcd3460833a8610/modules.d/45net-lib/netroot.sh#L78 (thx @cwize1 for find it).
