### ISSUE TITLE
Warning running with -H: grep: warning: stray \ before x

### ISSUE THREAD

**Issue by gene-git** [dracut-ng/dracut-ng#79]
**Describe the bug**
When using hostonly dracut triggers grep warning:
```
...
dracut[I]: *** Including module: rootfs-block ***
grep: warning: stray \ before x
dracut[I]: *** Including module: terminfo ***
...
```

**Distribution used**
  Archlinux

**Dracut version**
  Released 060 and git head as of commit 7f35206e6eb0f4c63636e114229276d76f381230

**Init system**
  systemd

**To Reproduce**
  dracut -H ...

**Expected behavior**
  No warnings from greo

**Additional context**
  bash: 5.2.026
  grep: 3.11

**Comment by gene-git** [comment]
Right - sorry about the duplicate.

**Comment by gene-git** [comment]
Trying to track this down So far I have not found the culprit.
It is possible the warning is coming from outside dracut itself with grep called using full path.

I tried the following.  

1) Create the script /tmp/xxx/grep:
```
#!/usr/bin/bash
#
echo "XXX : \"grep ${@}\"" >> /tmp/AAA
/usr/bin/grep "${@}" 2>&1 >> /tmp/AAA
/usr/bin/grep "${@}"
```
Ran dracut with PATH=/tmp/xxx:$PATH
Warning is still printed as above - however the file /tmp/AAA doesn't show it - it only has:

```
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /usr/lib/dracut/dracut.conf.d/70-nvmf-autoconnect.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf.d/bluetooth.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf.d/crypt.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf.d/mdraid.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf.d/plymouth.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf.d/useful.conf"
XXX : "grep -H -e ^[^#]*[+]=\("[^ ]\|.*[^ ]"\) /etc/dracut.conf.d/video.conf"
```

2) Ran each of the above grep's manually and none produced the warning.

3) Checked sources /usr/bin/grep.

4) I observed that my dummy grep was NOT called between rootfs-block and terminfo.

5) I searched the bash code for any PATH being set which might exclude my PATH env.

6) Went over commit  86c8a5a but didn't see any red flags.

I have not yet tried replacing the system grep to track this down.

Using this did not capture all grep calls - so I do suspect its called outside dracut and with full path.

**Comment by thesamesam** [comment]
Not sure if I'm stating something known, but this warning is pretty new in grep. See https://git.savannah.gnu.org/cgit/grep.git/commit/?id=e7f8e8eb1fd41b308ee10741bbd8068acc1847c2.

Is it definitely a regression?

**Comment by gene-git** [comment]
Thanks @thesamesam - hard to say what the significance is until we know what is triggering the warning. 

dracut appears to be working fine - and quite likely it's not causing an issue at the moment.  And my view is whatever causes this, is most likely outside of dracut code itself.

Nonethelss, be  good to confirm to know what exactly is causing the warning,  and then we can decide what, if anything, needs to be done.

**Comment by LaszloGombos** [comment]
Closing based on the feedback at https://github.com/dracut-ng/dracut-ng/pull/572#issuecomment-2295308380
