### ISSUE TITLE
Nothing depends on systemd-pcrphase

### ISSUE THREAD

**Issue by ossimoi** [dracut-ng/dracut-ng#92]
**Describe the bug**
systemd-pcrphase module needs to be manually added because no other module depends on it and check() returns 255 if the binaries exist.

**Distribution used**
Gentoo

**Dracut version**
060_pre20240104-r4^t

**Init system**
Systemd

**Expected behavior**
systemd-pcrphase is added to the initramfs when secureboot and TPM2 measurements are enabled.

**Additional context**
Does measured boot require a separate config flag, or would it be better if dracut recognizes if measuring is enabled by default?

**Comment by jozzsi** [comment]
https://github.com/dracut-ng/dracut-ng/pull/1830
