### ISSUE TITLE
detect and generate initrd.img-${kernel}

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#99]
https://www.freedesktop.org/wiki/Specifications/BootLoaderSpec/ refers to initramfs as "initrd".

One of the most popular distro's (Debian) expects /boot/initrd.img-${kernel} instead of initramfs-${kernel}.img, see https://kernel-team.pages.debian.net/kernel-handbook/ch-packaging.html#s-arch-dep

Let's look for a way to detect in a reliable way what should be the default output file that is more inclusive.

Possibly related openSUSE patch downstream: https://github.com/dracutdevs/dracut/commit/f68649cf55ca4545ed8304435c9c7315846c45a4

**Comment by nabijaczleweli** [comment]
Rather than a "detect" I this needs to be a config-time option (or, equivalently, a `nameinitrd() { echo "/boot/initramfs-$1.img"; }` with a distro drop-in sourced afterward; but this doesn't fix the manual, so just a config-time option).
